all: include comments kernels callargs

include: include.cpp
	g++ include.cpp -o include

comments: comments.cpp
	g++ comments.cpp -o comments

kernels: kernels.cpp
	g++ kernels.cpp -o kernels

callargs: callargs.cpp
	g++ callargs.cpp -o callargs


