char kernelstr[] = 
"#define GPU_SIMDS	4\n"
"#define GPU_MAXBLOCK	4\n"
"\n"
"#define LOCAL_WORK_SIZE	GPU_MAXBLOCK\n"
"#define GLOBAL_WORK_SIZE	(GPU_SIMDS * GPU_MAXBLOCK)\n"
"#define NPROC	GLOBAL_WORK_SIZE\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"float mul(float a, float b)\n"
"{\n"
"	return a * b;\n"
"}\n"
"__kernel void VecAdd(__global float *a, __global float *b, __global float *out)\n"
"{\n"
"	int iproc = get_global_id(0);\n"
"	out[iproc] = a[iproc] + b[iproc];\n"
"}\n"
"__kernel void VecMul(__global float *a, __global float *b, __global float *out)\n"
"{\n"
"	int iproc = get_global_id(0);\n"
"	/*out[iproc] = a[iproc] * b[iproc];*/\n"
"	out[iproc] = mul(a[iproc], b[iproc]);\n"
"}\n"
;
